---
- name: Configuración de servidor Apache
  hosts: webserver
  become: true

  tasks:
  - name: Actualizar lista de paquetes
    apt:
      update_cache: true

  - name: Instalar Apache
    apt:
      name: apache2
      state: present

  - name: Configurar firewall
    ufw:
       rule: allow
       port: '80'
       proto: tcp

  - name: Eliminar HTML
    file:
      path: /var/www/html/index.html
      state: absent

  - name: Crear Index.html
    file:
      path: /var/www/html/index.html
      state: touch

  - name: Escribir contenido de la página
    lineinfile:
      path: /var/www/html/index.html
      line: "¡Hola, chavales! He resucitado la máquina."

  - name: Habilitar y comenzar Apache
    service:
      name: apache2
      state: started
