---
- name: Configurando VSFTPD y Creación Usuario
  hosts: webserver
  become: true
  vars:
    username: pacoalba
    password: hannahmontana
    home_dir: /home/pacoalba

    # Changelog: securización de ftp. Creamos una variable con el directorio en el que nuestro usuario comenzará su andadura en el servidor FTP.

    ftp_dir: /opt/shared

  tasks:
    - name: Creando directorio de inicio del usuario
      file:
        path: "{{ home_dir }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755

    - name: Creando a Paco Alba
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        createhome: no
        home: "{{ home_dir }}"
        shell: /bin/bash
        comment: "Usuario creado"

    - name: Instalando VSFTPD
      apt: name=vsftpd update_cache=yes state=latest force_apt_get=yes
      tags: [ system ]
    - name: Configurando VSFTPD
      template:
        src: "files/vsftpd.conf"
        dest: "/etc/vsftpd.conf"
      notify: Reload VSFTPD
      tags: [ ftp ]

    # Securización FTP: vamos a enjaular a los usuarios incluídos en la lista

    - name: Configurando VSFTPD
      copy:
       src: "./vsftpd_backup.conf"
       dest: "/etc/vsftpd.conf"
      notify: Reload VSFTPD
      tags: [ ftp ]

# Securización FTP: creamos el directorio raíz en el que va a iniciar sesión pacoalba

    - name: Creacion directorio FTP y cambio de permisos
      file:
        path: /opt/shared
        state: directory
        owner: pacoalba
        group: pacoalba
        mode: '0755'

# Securización FTP: añadimos el usuario pacoalba a la lista de usuarios

    - name: Agregar a pacoalba al archivo /etc/vsftpd.userlist
      lineinfile:
        path: /etc/vsftpd.userlist
        line: 'pacoalba'
        state: present

# Se podría afinar más creando un grupo de usuarios para FTP (ej: alegriagroup) y
# de manera más genérica agregar a este grupo los usuarios que tengan acceso al FTP conforme se vayan creando

  handlers:
    - name: Reload VSFTPD
      service:
        name: vsftpd
        state: reloaded

    - name: Restart VSFTPD
      service:
        name: vsftpd
        state: restarted