---
- name: Configuración LAMP con WordPress
  hosts: webserver
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Instalando prerequisitos
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
      tags: [ system ]

    - name: Instalando LAMP
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]
      tags: [ system ]

    - name: Instalando Extensiones PHP
      apt: name={{ item }} update_cache=yes state=latest
      loop: "{{ php_modules }}"
      tags: [ system ]

# Configuración Apache
    - name: Creando Documento Root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: '0755'
      tags: [ apache ]

    - name: Configurando un VirtualHost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache
      tags: [ apache ]

    - name: Habilitando módulo de reescritura
      shell: /usr/sbin/a2enmod rewrite
      notify: Reload Apache
      tags: [ apache ]

    - name: Habilitando nuevo sitio
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache
      tags: [ apache ]

# Importamos BDD ya creada de WP

    - name: Importando BDD WP a /tmp
      template:
        src: "files/sqldump.sql"
        dest: "/tmp"
      tags: [ mysql ]

# Configuración MySQL
    - name: Estableciendo la contraseña de Root
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /run/mysqld/mysqld.sock
      tags: [ mysql, mysql-root ]

    - name: Eliminando todas las cuentas anónimas
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

    - name: Creando un usuario para WordPress
      mysql_user:
        name: "{{ mysql_user}}"
        password: "{{ mysql_password}}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

    - name: Eliminando la base de datos Test
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

# Configurando Firewall Linux
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
      tags: [ system ]

# Configuración WordPress
    - name: Descargando la versión más reciente de WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/{{ http_host }}"
        remote_src: yes
        creates: "/var/www/{{ http_host }}/wordpress"
      tags: [ wordpress ]

    - name: Estableciendo carpeta propietaria
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      tags: [ wordpress ]

    - name: Estableciendo permisos a directorios
      shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type d -exec chmod 750 {} \\;"
      tags: [ wordpress ]

    - name: Configurando wp-config
      template:
        src: files/wp-config.php.j2
        dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"
      tags: [ wordpress ]

    - name: Restaurando BDD
      community.mysql.mysql_db:
        name: wordpress
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: import
        target: /tmp/sqldump.sql

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
         name: apache2
         state: restarted
